// Importing necessary modules and components
import { JetBrains_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import NavList from '@/components/NavList'

// Setting up JetBrains_Mono font with latin subset
const inter = JetBrains_Mono({ subsets: ['latin'] })

// Metadata for the application
export const metadata = {
  title: 'Crowgram',
  description: 'Generated by Crowgram bot',
}

// RootLayout component which wraps around all other components
export default function RootLayout({ children }) {
  return (
    // HTML structure of the application
    <html lang="en">
      <body className={inter.className}>
        <main className=' flex h-[100vh]'>
          <Header /> {/* Header component */}
          <aside className=' border-r border-white hidden  md:block fixed top-[10vh] w-[300px] h-full  px-4  bg-black ' >
            <NavList /> {/* Navigation List component */}
          </aside> 
          <div className=' z-10 w-full md:ml-[300px] relative top-[10vh]  ' >
            {children} {/* Child components */}
          </div>
        </main>  
      </body>
    </html>
  )
}